"""Notification service for alerts and emails."""

import os
import smtplib
import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from utils.time_utils import now_utc_iso


logger = logging.getLogger(__name__)


def send_mismatch_email(resident_id: str, mismatch_count: int) -> bool:
    """
    Send email alert for resident status mismatch.
    
    Args:
        resident_id: Resident identifier
        mismatch_count: Number of consecutive mismatches
    
    Returns:
        bool: True if email sent successfully, False otherwise
    """
    try:

        email_sender = os.getenv("EMAIL_SENDER")
        email_password = os.getenv("EMAIL_PASSWORD")
        # Support multiple recipients: EMAIL_RECIPIENTS can be a comma-separated list.
        recipients_raw = os.getenv("EMAIL_RECIPIENTS") 
        smtp_server = os.getenv("SMTP_SERVER")
        smtp_port = int(os.getenv("SMTP_PORT", "465"))

        if not all([email_sender, email_password, recipients_raw, smtp_server]):
            logger.error("SMTP configuration incomplete")
            raise RuntimeError("SMTP configuration incomplete")

        # Parse recipients into a list, trimming whitespace and ignoring empties
        recipients = [r.strip() for r in recipients_raw.split(",") if r.strip()]
        if not recipients:
            logger.error("No valid email recipients configured")
            raise RuntimeError("No valid email recipients configured")

        msg = MIMEMultipart()
        msg["From"] = email_sender
        msg["To"] = ", ".join(recipients)
        msg["Subject"] = f" VMedD Server Monitor Alert"

        body = f"""
                    <html>
            <body style="font-family: Arial, Helvetica, sans-serif; color: #333;">
                
                <h2 style="color: #b00020; margin-bottom: 10px;">
                VMedD Server Monitor – Alert
                </h2>

                <p>
                This alert indicates a detected inconsistency in server behavior that
                requires attention.
                </p>

                <table style="border-collapse: collapse; margin-top: 10px;">
                <tr>
                    <td style="padding: 6px 12px; font-weight: bold;">Resident</td>
                    <td style="padding: 6px 12px;">{resident_id}</td>
                </tr>
                <tr>
                    <td style="padding: 6px 12px; font-weight: bold;">Issue</td>
                    <td style="padding: 6px 12px;">
                    WebDAV upload status does not match the portal (browser) download status.
                    This may indicate a server-side processing or synchronization issue.
                    </td>
                </tr>
                <tr>
                    <td style="padding: 6px 12px; font-weight: bold;">Consecutive Mismatches</td>
                    <td style="padding: 6px 12px;">{mismatch_count}</td>
                </tr>
                <tr>
                    <td style="padding: 6px 12px; font-weight: bold;">Timestamp (UTC)</td>
                    <td style="padding: 6px 12px;">{now_utc_iso()}</td>
                </tr>
                </table>

                <p style="margin-top: 16px;">
                Please investigate the server and related services to ensure normal
                operation is restored.
                </p>

                <p style="font-size: 12px; color: #777;">
                This is an automated message generated by the VMedD Server Monitoring
                system.
                </p>

            </body>
            </html>

        """

        msg.attach(MIMEText(body, "html"))

        with smtplib.SMTP_SSL(smtp_server, smtp_port) as server:
            server.login(email_sender, email_password)
            # send_message accepts an explicit list of recipients
            server.send_message(msg, to_addrs=recipients)

        logger.info(f"Alert email sent for resident {resident_id}")
        return True

    except Exception:
        logger.exception("Failed to send mismatch email")
        return False
    


def send_recovery_email(resident_id: str) -> bool:
    """
    Send email notification indicating server recovery for a resident.

    Args:
        resident_id: Resident identifier

    Returns:
        bool: True if email sent successfully, False otherwise
    """
    try:
        email_sender = os.getenv("EMAIL_SENDER")
        email_password = os.getenv("EMAIL_PASSWORD")
        recipients_raw = os.getenv("EMAIL_RECIPIENTS")
        smtp_server = os.getenv("SMTP_SERVER")
        smtp_port = int(os.getenv("SMTP_PORT", "465"))

        if not all([email_sender, email_password, recipients_raw, smtp_server]):
            logger.error("SMTP configuration incomplete")
            raise RuntimeError("SMTP configuration incomplete")

        recipients = [r.strip() for r in recipients_raw.split(",") if r.strip()]
        if not recipients:
            logger.error("No valid email recipients configured")
            raise RuntimeError("No valid email recipients configured")

        msg = MIMEMultipart()
        msg["From"] = email_sender
        msg["To"] = ", ".join(recipients)
        msg["Subject"] = f"VMedDServer Monitor Recovery"

        body = f"""
                    <html>
            <body style="font-family: Arial, Helvetica, sans-serif; color: #333;">
                
                <h2 style="color: #2e7d32; margin-bottom: 10px;">
                VMedD Server Monitor – Recovery
                </h2>

                <p>
                This notification confirms that the monitored server functionality has
                returned to a stable and healthy state.
                </p>

                <table style="border-collapse: collapse; margin-top: 10px;">
                <tr>
                    <td style="padding: 6px 12px; font-weight: bold;">Resident</td>
                    <td style="padding: 6px 12px;">{resident_id}</td>
                </tr>
                <tr>
                    <td style="padding: 6px 12px; font-weight: bold;">Status</td>
                    <td style="padding: 6px 12px;">
                    WebDAV upload status and portal (browser) status are consistent.
                    </td>
                </tr>
                <tr>
                    <td style="padding: 6px 12px; font-weight: bold;">Verification</td>
                    <td style="padding: 6px 12px;">
                    Status has matched continuously for the configured recovery window.
                    </td>
                </tr>
                <tr>
                    <td style="padding: 6px 12px; font-weight: bold;">Timestamp (UTC)</td>
                    <td style="padding: 6px 12px;">{now_utc_iso()}</td>
                </tr>
                </table>

                <p style="margin-top: 16px;">
                No further action is required at this time. Monitoring will continue
                automatically.
                </p>

                <p style="font-size: 12px; color: #777;">
                This is an automated message generated by the VMedD Server Monitoring
                system.
                </p>

            </body>
            </html>

        """

        msg.attach(MIMEText(body, "html"))

        with smtplib.SMTP_SSL(smtp_server, smtp_port) as server:
            server.login(email_sender, email_password)
            server.send_message(msg, to_addrs=recipients)

        logger.info(f"Recovery email sent for resident {resident_id}")
        return True

    except Exception:
        logger.exception("Failed to send recovery email")
        return False
